# Generated by Django 5.0.3 on 2024-03-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('image1', models.ImageField(upload_to='service_images/')),
                ('image2', models.ImageField(upload_to='service_images/')),
                ('image3', models.ImageField(upload_to='service_images/')),
            ],
        ),
    ]
