# Generated by Django 5.0.3 on 2024-03-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
