# Generated by Django 5.0.3 on 2024-04-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phno',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
