# Generated by Django 5.0.3 on 2024-04-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0009_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
