# Generated by Django 5.0.3 on 2024-04-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0011_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='spname',
            new_name='username',
        ),
    ]
