# Generated by Django 5.0.3 on 2024-04-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0012_rename_spname_order_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
